modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/ItemOutlines/issues"
license="MIT"

[[mods]]
modId="itemoutlines"
version="${file.jarVersion}"
displayName="Item Outlines"
displayURL="https://www.curseforge.com/minecraft/mc-mods/item-outlines"
authors="Mrbysco"
description='''
Adds configurable item outlines
'''
[[dependencies.itemoutlines]]
modId="minecraft"
type="required"
versionRange="[26.1.1,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="itemoutlines.mixins.json"